#ifndef GUARD_CONSTANTS_SPEAKER_NAMES_H
#define GUARD_CONSTANTS_SPEAKER_NAMES_H

enum SpeakerNames {
    SP_NAME_NONE = 0,
    SP_NAME_MOM,
    SP_NAME_PLAYER,
    SP_NAME_RIVAL,
    SP_NAME_LEAF,
    SP_NAME_OAK,
    SP_NAME_BROCK,
    SP_NAME_MISTY,
    SP_NAME_SURGE,
    SP_NAME_ERIKA,
    SP_NAME_KOGA,
    SP_NAME_SABRINA,
    SP_NAME_BLAINE,
    SP_NAME_GIOVANNI,
    SP_NAME_LORELEI,
    SP_NAME_BRUNO,
    SP_NAME_AGATHA,
    SP_NAME_LANCE,
    SP_NAME_COUNT
};

#endif // GUARD_CONSTANTS_SPEAKER_NAMES_H
